//! Integration tests for ONNX → weaver-IR parsing.
//!
//! These tests load real `.onnx` fixture files generated by the companion
//! Python script (`generate_fixtures.py`) and verify that the parser
//! produces a valid, well-typed IR graph.

#![cfg(feature = "onnx")]

use std::collections::HashMap;

use gir::data::TensorData;
use gir::graph::Graph;
use gir::onnx::{OnnxError, parse_onnx};
use gir::op::OpKind;

// ─── Helpers ────────────────────────────────────────────────────────

/// Load a fixture file from `tests/fixtures/<name>`.
fn load_fixture(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"),);
    std::fs::read(&path).unwrap_or_else(|e| panic!("failed to read fixture {path}: {e}"))
}

/// Parse a fixture file, panicking on error.
fn parse_fixture(name: &str) -> Graph {
    let bytes = load_fixture(name);
    parse_onnx(&bytes).unwrap_or_else(|e| panic!("failed to parse {name}: {e}"))
}

/// Collect the op kinds of every non-Constant node in topological order.
fn op_sequence(graph: &Graph) -> Vec<&OpKind> {
    graph
        .nodes()
        .iter()
        .filter(|n| n.op != OpKind::Constant)
        .map(|n| &n.op)
        .collect()
}

// ─── Simple MLP ─────────────────────────────────────────────────────

#[test]
fn parse_simple_mlp() {
    let g = parse_fixture("simple_mlp.onnx");

    assert_eq!(g.name, "simple_mlp");

    // The MLP should have: Gemm → Relu → Gemm → Softmax (4 compute nodes).
    let ops = op_sequence(&g);
    assert_eq!(ops.len(), 4, "expected 4 compute ops, got {ops:?}");
    assert_eq!(ops[0], &OpKind::FullyConnected); // Gemm
    assert_eq!(ops[1], &OpKind::Relu);
    assert_eq!(ops[2], &OpKind::FullyConnected); // Gemm
    assert_eq!(ops[3], &OpKind::Softmax);

    // The graph should carry one free symbolic dimension ("N").
    let syms = g.free_symbols();
    assert!(
        syms.contains(&"N".to_owned()),
        "expected symbolic dim 'N', got {syms:?}",
    );

    // Evaluate shapes with a concrete batch size.
    let env: HashMap<&str, u64> = [("N", 4)].into();
    let shapes = g.evaluate_shapes(&env);

    // The input should be (4, 784).
    let input_shape = shapes.get(&g.inputs[0]).expect("input shape missing");
    assert_eq!(input_shape, &[4, 784]);

    // The output should be (4, 10).
    let output_shape = shapes.get(&g.outputs[0]).expect("output shape missing");
    assert_eq!(output_shape, &[4, 10]);
}

// ─── Tiny ConvNet ───────────────────────────────────────────────────

#[test]
fn parse_tiny_convnet() {
    let g = parse_fixture("tiny_convnet.onnx");

    assert_eq!(g.name, "tiny_convnet");

    // Expected compute ops: Conv → BatchNorm → Relu → MaxPool
    //                      → GlobalAvgPool → Reshape → Gemm
    let ops = op_sequence(&g);
    assert_eq!(ops.len(), 7, "expected 7 compute ops, got {ops:?}");
    assert_eq!(ops[0], &OpKind::Conv2d);
    assert_eq!(ops[1], &OpKind::BatchNorm);
    assert_eq!(ops[2], &OpKind::Relu);
    assert_eq!(ops[3], &OpKind::MaxPool2d);
    assert_eq!(ops[4], &OpKind::GlobalAvgPool);
    assert_eq!(ops[5], &OpKind::Reshape);
    assert_eq!(ops[6], &OpKind::FullyConnected); // Gemm

    // Symbolic batch dim.
    let syms = g.free_symbols();
    assert!(syms.contains(&"N".to_owned()));

    // Evaluate with batch = 2.
    let env: HashMap<&str, u64> = [("N", 2)].into();
    let shapes = g.evaluate_shapes(&env);

    // Input: (2, 1, 28, 28).
    let input_shape = shapes.get(&g.inputs[0]).expect("input shape");
    assert_eq!(input_shape, &[2, 1, 28, 28]);

    // Output: (2, 10).
    let output_shape = shapes.get(&g.outputs[0]).expect("output shape");
    assert_eq!(output_shape, &[2, 10]);
}

// ─── Mini ResNet Block ──────────────────────────────────────────────

#[test]
fn parse_mini_resnet_block() {
    let g = parse_fixture("mini_resnet_block.onnx");

    assert_eq!(g.name, "mini_resnet_block");

    // Expected compute ops:
    //   Conv → BN → Relu → Conv → BN → Add → Relu
    //   → GlobalAvgPool → Reshape → Gemm
    let ops = op_sequence(&g);
    assert_eq!(ops.len(), 10, "expected 10 compute ops, got {ops:?}");
    assert_eq!(ops[0], &OpKind::Conv2d);
    assert_eq!(ops[1], &OpKind::BatchNorm);
    assert_eq!(ops[2], &OpKind::Relu);
    assert_eq!(ops[3], &OpKind::Conv2d);
    assert_eq!(ops[4], &OpKind::BatchNorm);
    assert_eq!(ops[5], &OpKind::Add);
    assert_eq!(ops[6], &OpKind::Relu);
    assert_eq!(ops[7], &OpKind::GlobalAvgPool);
    assert_eq!(ops[8], &OpKind::Reshape);
    assert_eq!(ops[9], &OpKind::FullyConnected); // Gemm

    // Symbolic batch dim.
    let syms = g.free_symbols();
    assert!(syms.contains(&"N".to_owned()));

    // Evaluate with batch = 1.
    let env: HashMap<&str, u64> = [("N", 1)].into();
    let shapes = g.evaluate_shapes(&env);

    // Input: (1, 16, 8, 8).
    let input_shape = shapes.get(&g.inputs[0]).expect("input shape");
    assert_eq!(input_shape, &[1, 16, 8, 8]);

    // Output: (1, 10).
    let output_shape = shapes.get(&g.outputs[0]).expect("output shape");
    assert_eq!(output_shape, &[1, 10]);
}

#[test]
fn parse_resnet50_v2_7() {
    let g = parse_fixture("resnet50-v2-7.onnx");
    assert_eq!(g.parameters(), 25_595_062);

    let node = g.nodes().iter().find(|n| n.name.as_deref() == Some("resnetv24_conv0_fwd"))
        .expect("could not find first conv node");
    let output = node.outputs[0];
    let output = g.value_info(output)
        .expect("could not find conv value info");
    assert_eq!(output.name.as_deref(), Some("resnetv24_conv0_fwd"));
    println!("shape = {}", output.shape);
}

// ─── Residual add preserves symbolic batch ──────────────────────────

#[test]
fn resnet_block_residual_propagates_batch_dim() {
    let g = parse_fixture("mini_resnet_block.onnx");

    // The Add node (residual skip-connection) should still carry the
    // symbolic batch dimension in its output shape.
    let add_node = g
        .nodes()
        .iter()
        .find(|n| n.op == OpKind::Add)
        .expect("Add node missing");
    let add_output = add_node.outputs[0];
    let add_info = g.value_info(add_output).expect("Add output info");

    // The shape should contain "N" as its first dimension.
    let free = add_info.shape.free_symbols();
    assert!(
        free.contains(&"N".to_owned()),
        "expected symbolic 'N' in Add output shape, got {free:?}",
    );
}

// ─── Error path: unsupported op ─────────────────────────────────────

#[test]
fn unsupported_op_produces_error() {
    // Build a minimal ONNX model with an op we don't support (e.g. "Where").
    use prost::Message;

    // Manually construct a minimal protobuf.
    let model_bytes = {
        use gir::onnx::proto;

        let node = proto::NodeProto {
            op_type: "Where".to_owned(),
            name: "bad_where".to_owned(),
            input: vec!["cond".to_owned(), "x".to_owned(), "y".to_owned()],
            output: vec!["out".to_owned()],
            ..Default::default()
        };

        let inp = |n: &str, dt: i32| proto::ValueInfoProto {
            name: n.to_owned(),
            r#type: Some(proto::TypeProto {
                denotation: String::new(),
                value: Some(proto::type_proto::Value::TensorType(
                    proto::type_proto::Tensor {
                        elem_type: dt,
                        shape: Some(proto::TensorShapeProto {
                            dim: vec![proto::tensor_shape_proto::Dimension {
                                denotation: String::new(),
                                value: Some(proto::tensor_shape_proto::dimension::Value::DimValue(
                                    4,
                                )),
                            }],
                        }),
                    },
                )),
            }),
            doc_string: String::new(),
            metadata_props: vec![],
        };

        let graph = proto::GraphProto {
            name: "bad_graph".to_owned(),
            node: vec![node],
            input: vec![inp("cond", 9), inp("x", 1), inp("y", 1)],
            output: vec![inp("out", 1)],
            ..Default::default()
        };

        let model = proto::ModelProto {
            graph: Some(graph),
            opset_import: vec![proto::OperatorSetIdProto {
                domain: String::new(),
                version: 17,
            }],
            ..Default::default()
        };

        model.encode_to_vec()
    };

    let result = parse_onnx(&model_bytes);
    assert!(result.is_err());
    let err = result.unwrap_err();
    assert!(
        matches!(err, OnnxError::UnsupportedOp { .. }),
        "expected UnsupportedOp, got {err}",
    );
}

// ─── Constant data extraction ───────────────────────────────────────

#[test]
fn mlp_weights_are_extracted() {
    let g = parse_fixture("simple_mlp.onnx");

    // The MLP has 4 initializers: W1 (128×784), B1 (128), W2 (10×128), B2 (10).
    // All should have TensorData attached.
    assert!(
        g.num_constants() >= 4,
        "expected at least 4 constants, got {}",
        g.num_constants(),
    );

    // Find a Constant node whose output is named "W1".
    let w1_node = g
        .nodes()
        .iter()
        .find(|n| n.op == OpKind::Constant && n.name.as_deref() == Some("W1"))
        .expect("W1 constant node missing");

    let w1_id = w1_node.outputs[0];
    let w1_data: &TensorData = g.constant_data(w1_id).expect("W1 data missing");

    // W1 is (128, 784) F32 → 128 * 784 = 100_352 elements × 4 bytes.
    assert_eq!(w1_data.len(), 128 * 784);
    assert_eq!(w1_data.dtype(), gir::dtype::DType::F32);
    assert_eq!(w1_data.size_in_bytes(), 128 * 784 * 4);

    // Verify we can read the data back as f32.
    let floats = w1_data.as_f32s().expect("should be f32 data");
    assert_eq!(floats.len(), 128 * 784);
    // Data should not be all zeros (we used random init in the generator).
    assert!(
        floats.iter().any(|&v| v != 0.0),
        "expected non-zero weight data",
    );
}

#[allow(clippy::identity_op)]
#[test]
fn convnet_conv_weights_extracted() {
    let g = parse_fixture("tiny_convnet.onnx");

    // Find the conv weight constant (8, 1, 3, 3).
    let conv_w_node = g
        .nodes()
        .iter()
        .find(|n| n.op == OpKind::Constant && n.name.as_deref() == Some("conv_w"))
        .expect("conv_w constant missing");

    let data = g
        .constant_data(conv_w_node.outputs[0])
        .expect("conv_w data missing");

    assert_eq!(data.len(), 8 * 1 * 3 * 3); // 72 elements
    assert_eq!(data.dtype(), gir::dtype::DType::F32);
}
