//! ONNX model parser — reads ONNX protobuf bytes and constructs the weaver IR.
//!
//! This module is gated behind the `onnx` feature flag.
//!
//! # Usage
//!
//! ```no_run
//! use gir::onnx::parse_onnx;
//!
//! let bytes = std::fs::read("model.onnx").unwrap();
//! let graph = parse_onnx(&bytes).unwrap();
//! println!("{graph}");
//! ```

mod parser;

pub use parser::{OnnxError, parse_onnx};

/// Generated protobuf types from the ONNX spec.
///
/// These are auto-generated by `prost-build` from `proto/onnx.proto3`.
#[allow(clippy::doc_markdown)]
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}
